modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/ColMarek/fasterfurnaces/issues"
license="MIT License"

[[mods]]
modId = "fasterfurnaces"
version = "${file.jarVersion}"
displayName = "Faster Furnaces"
updateJSONURL = "http://colmarek.github.com/"
displayURL = "http://colmarek.github.com/"
logoFile = "icon.png"
authors = "ColMarek"
description = '''
This mod adds new furnaces that are faster than the vanilla one.
'''

[[dependencies.fasterfurnaces]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fasterfurnaces]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3]"
ordering = "NONE"
side = "BOTH"
